### ISSUE TITLE
High Score, Likes and Comments Janky UI on Higher Count #

### ISSUE THREAD

**Issue by shchoi22** [cubros/vread#17]
![image](https://user-images.githubusercontent.com/4170321/38158543-94636bac-34d1-11e8-92c6-3edc1a149a5d.png)

**Comment by tyherox** [comment]
@shchoi22 Hmm... I checked out a couple of other sites like Quora to see how they handled issues like this. This seems to be their solution for large numbers: 

<img width="375" alt="screen shot 2018-03-31 at 5 55 35 pm" src="https://user-images.githubusercontent.com/10558097/38161599-ed485be8-350c-11e8-9664-33dba590d7bf.png">

Are you open to trying this out? If not, I'll find a solution by editing the layout.

**Comment by tyherox** [comment]
I'll ask 무아님 for her opinion as well.

**Comment by tyherox** [comment]
PR #27 solved this, closing.

**Comment by tyherox** [comment]
Reopening until PR is made for this issue.
