### ISSUE TITLE
자동 플레이가 화면 상에 들어왔을 때가 아니라 전체적으로 동시 진행되는데 이래서 버벅이는  건지, performance 넘나 느림 - play button 삽입하거나 부분적auto play 등 해결 방안

### ISSUE THREAD

**Issue by shchoi22** [cubros/vread#38]
1. Create backend function to save screenshot and link it to post object in firebase. (Stan)
2. If auto-play off, display screenshot with clickable button to start vr content. (John)
3. If auto-play on (default), start vr content only when screen is displaying that preview content. Other two (post on top and bottom) should only be loaded in virtual dom and ready to be mounted when scrolled to. (John)

**Comment by tyherox** [comment]
Should we close this now?

**Comment by shchoi22** [comment]
Closing
