### ISSUE TITLE
사파리에서 구글 로그인하면 무한 새창 반복 ( safari private mode), username 계속 적으로 생성하게 만듬, sign up 안됨, 소셜 로그인

### ISSUE THREAD

**Issue by tyherox** [cubros/vread#58]

**Comment by shchoi22** [comment]
Cannot replicate in any other browser than safari private mode. Solution for right now is not supporting safari private mode. Error message in https://github.com/cubros/vread/pull/73 should take care of most issues. Closing ticket.
