### ISSUE TITLE
마이 페이지 접속이 원활하지 않음

### ISSUE THREAD

**Issue by tyherox** [cubros/vread#63]

**Comment by tyherox** [comment]
Can't replicate, need more information

**Comment by shchoi22** [comment]
@tyherox I thought this was post loading issue but actually it wasn't. Will need more information to replicate. Closing ticket for now.

**Comment by shchoi22** [comment]
Reopening until wednesday meeting.

**Comment by shchoi22** [comment]
Resolving as it did not come up during meeting.
