### ISSUE TITLE
Unable to load user background images

### ISSUE THREAD

**Issue by tyherox** [cubros/vread#76]
<img width="345" alt="screen shot 2018-04-30 at 3 52 28 pm" src="https://user-images.githubusercontent.com/10558097/39417339-8e2a44b6-4c8e-11e8-8415-eeafad846b51.png">

Scenes in the homepage that have user backgrounds give the error above.

**Comment by shchoi22** [comment]
Fixed by setting cors (using gutil):
```
[
    {
      "origin": ["*"],
      "method": ["GET"],
      "maxAgeSeconds": 3600
    }
]
```
Closing issue.
